// GENERATED by scripts/generate-product-links.ts — do not edit by hand.
//
// The catalogue as a flat list of links, for site-wide navigation. The footer renders these on
// every page, which is what gives each product URL an entry point from everywhere on the site
// rather than only from /products and the sitemap.
//
// Names are de-duplicated: two catalogue rows are both called "Ni Custom", and two identical
// links with identical anchor text tell a search engine nothing about either page.

export type ProductLink = { slug: string; name: string };

export const PRODUCT_LINKS: readonly ProductLink[] = [
  { slug: "21700-2p-h-type-precision", name: "21700 2P H-type" },
  { slug: "Copper-Busbar", name: "Copper Busbar" },
  { slug: "ni-18650-2p-h-type", name: "Ni 18650 2P H-Type Nickel Strip (ASTM B16)" },
  { slug: "ni-18650-2p-h-type-fuse-type", name: "Ni 18650 2P H-Type Nickel Strip (ASTM B17)" },
  { slug: "ni-18650-2p-zig-zag-no-fuse-type", name: "Ni 18650 2P ZIG-ZAG" },
  { slug: "ni-18650-3p-h-type", name: "Ni 18650 3P H-type" },
  { slug: "ni-18650-4p-h-type", name: "Ni 18650 4P H-type" },
  { slug: "ni-21700-2p-h-type-v3", name: "Ni 21700 2P H-Type Nickel Strip" },
  { slug: "ni-21700-4p-h-type", name: "Ni 21700 4P H-type" },
  { slug: "ni-32650-2p-h-type", name: "Ni 32650 2P H-type" },
  { slug: "ni-customizable", name: "Ni Custom" },
  { slug: "ni-fuse-type-21700-2p-h-type-double-fuse", name: "Ni Fuse type 21700" },
  { slug: "ni-fuse-type-32700-2p-zig-zag-honeycomb", name: "Ni Fuse Type 32700" },
  { slug: "ni-fuse-type-18650-2p-h-type-honeycomb", name: "Ni Fuse-Type 18650 — H-Type Honeycomb" },
  { slug: "ni-fuse-type-18650-2p-zig-zag-honeycomb", name: "Ni Fuse-Type 18650 — Zig-Zag Honeycomb" },
  { slug: "Plain-Nickel-Strips", name: "Plain Nickel Strips" },
];
