// GENERATED by scripts/sync-product-images.ts — do not edit by hand.
//
// Maps each product slug to the descriptive filename its photo was saved under in
// public/img/products/. Both the image proxy in apiApp.ts and the <ProductThumbnail> fallback
// consult this before falling back to the generic placeholder, so a product with a local copy
// shows its own photo rather than the logo.
//
// The filename is not the slug: it is built from the product's name so the image URL reads as
// a description of the photo, which is one of the few things an image crawler can use. Old
// <slug>.webp URLs still resolve — both routing tables send a miss under /img/products/ to the
// /api/product-image proxy, which answers by slug.

const LOCAL_PRODUCT_IMAGE_FILES: ReadonlyMap<string, string> = new Map([
  ["21700-2p-h-type-precision", "21700-2p-h-type-precision-nickel-strip"],
  ["Copper-Busbar", "copper-busbar"],
  ["Plain-Nickel-Strips", "plain-nickel-strips"],
  ["ni-18650-2p-h-type", "ni-18650-2p-h-type-nickel-strip"],
  ["ni-18650-2p-h-type-fuse-type", "ni-18650-2p-h-type-nickel-strip-fuse"],
  ["ni-18650-2p-zig-zag-no-fuse-type", "ni-18650-2p-zig-zag-no-fuse-type-nickel-strip"],
  ["ni-18650-3p-h-type", "ni-18650-3p-h-type-nickel-strip"],
  ["ni-18650-4p-h-type", "ni-18650-4p-h-type-nickel-strip"],
  ["ni-21700-2p-h-type-v3", "ni-21700-2p-h-type-nickel-strip-v3"],
  ["ni-21700-4p-h-type", "ni-21700-4p-h-type-nickel-strip"],
  ["ni-32650-2p-h-type", "ni-32650-2p-h-type-nickel-strip"],
  ["ni-custom-custom", "ni-custom-nickel-strip"],
  ["ni-customizable", "ni-custom-customizable-nickel-strip"],
  ["ni-fuse-type-18650-2p-h-type-honeycomb", "ni-fuse-type-18650-h-type-honeycomb-2p-nickel-strip"],
  ["ni-fuse-type-18650-2p-zig-zag-honeycomb", "ni-fuse-type-18650-zig-zag-honeycomb-2p-nickel-strip"],
  ["ni-fuse-type-21700-2p-h-type-double-fuse", "ni-fuse-type-21700-2p-h-double-nickel-strip"],
  ["ni-fuse-type-32700-2p-zig-zag-honeycomb", "ni-fuse-type-32700-2p-zig-zag-honeycomb-nickel-strip"],
]);

/** Slugs with a downloaded photo on disk. */
export const LOCAL_PRODUCT_IMAGE_SLUGS: ReadonlySet<string> = new Set(
  LOCAL_PRODUCT_IMAGE_FILES.keys()
);

/** Root-relative path to the downloaded copy, or null when there is none. */
export function localProductImagePath(slug?: string | null): string | null {
  const clean = slug?.trim();
  if (!clean) return null;
  const file = LOCAL_PRODUCT_IMAGE_FILES.get(clean);
  return file ? `/img/products/${file}.webp` : null;
}
