// GENERATED by scripts/sync-product-images.ts — do not edit by hand.
//
// Slugs with a downloaded photo under public/img/products/. Both the image proxy in apiApp.ts
// and the <ProductThumbnail> fallback consult this before falling back to the generic
// placeholder, so a product with a local copy shows its own photo rather than the logo.

export const LOCAL_PRODUCT_IMAGE_SLUGS: ReadonlySet<string> = new Set([
  "21700-2p-h-type-precision",
  "Copper-Busbar",
  "Plain-Nickel-Strips",
  "ni-18650-2p-h-type",
  "ni-18650-2p-h-type-fuse-type",
  "ni-18650-2p-zig-zag-no-fuse-type",
  "ni-18650-3p-h-type",
  "ni-18650-4p-h-type",
  "ni-21700-2p-h-type-v3",
  "ni-21700-4p-h-type",
  "ni-32650-2p-h-type",
  "ni-custom-custom",
  "ni-customizable",
  "ni-fuse-type-18650-2p-h-type-honeycomb",
  "ni-fuse-type-18650-2p-zig-zag-honeycomb",
  "ni-fuse-type-21700-2p-h-type-double-fuse",
  "ni-fuse-type-32700-2p-zig-zag-honeycomb",
]);

/** Root-relative path to the downloaded copy, or null when there is none. */
export function localProductImagePath(slug?: string | null): string | null {
  const clean = slug?.trim();
  if (!clean || !LOCAL_PRODUCT_IMAGE_SLUGS.has(clean)) return null;
  return `/img/products/${encodeURIComponent(clean)}.webp`;
}
