-- Run this in Supabase SQL Editor to create and seed your database.

begin;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text unique not null,
  password text not null,
  role text not null default 'user',
  provider text,
  google_id text,
  avatar_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.user_preferences (
  id bigint generated by default as identity primary key,
  user_id bigint unique references public.users(id) on delete cascade,
  locale text,
  country_code text,
  currency text,
  postal_code text,
  preferences jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique not null,
  image text,
  description text
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  category_id bigint references public.categories(id) on delete set null,
  name text not null,
  slug text unique not null,
  description text,
  price numeric(12,2),
  image text,
  astm_value text,
  uns_value text,
  dimensions text,
  stock integer not null default 0,
  is_featured boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.ads (
  id bigint generated by default as identity primary key,
  title text not null,
  subtitle text,
  cta_text text,
  cta_url text,
  image_url text,
  badge text,
  discount_percent integer,
  show_banner boolean not null default true,
  show_popup boolean not null default true,
  is_active boolean not null default true,
  start_at timestamptz,
  end_at timestamptz,
  priority integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete set null,
  total_amount numeric(12,2),
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  quantity integer not null,
  price numeric(12,2)
);

create table if not exists public.visitor_logs (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete set null,
  path text,
  referrer text,
  user_agent text,
  geo_location text,
  timestamp timestamptz not null default now()
);

create table if not exists public.product_enquiries (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete set null,
  product_id bigint references public.products(id) on delete set null,
  product_name text,
  requirement text,
  full_name text not null,
  email text not null,
  phone text not null,
  company text,
  location text,
  quantity text,
  message text,
  created_at timestamptz not null default now()
);

create table if not exists public.quote_requests (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete set null,
  phone_country_code text,
  phone_number text,
  phone_full text,
  gst_number text,
  pin_code text,
  shipping_option text,
  subtotal numeric(12,2),
  gst numeric(12,2),
  total numeric(12,2),
  currency text,
  locale text,
  items_count integer,
  source text,
  user_agent text,
  created_at timestamptz not null default now()
);

create table if not exists public.quote_request_items (
  id bigint generated by default as identity primary key,
  quote_request_id bigint references public.quote_requests(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text,
  category_name text,
  quantity integer not null,
  unit_price numeric(12,2),
  line_total numeric(12,2)
);

create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, product_id)
);

create index if not exists idx_categories_slug on public.categories(slug);
create index if not exists idx_products_slug on public.products(slug);
create index if not exists idx_products_category_id on public.products(category_id);
create index if not exists idx_ads_active on public.ads(is_active);
create index if not exists idx_ads_priority on public.ads(priority);
create index if not exists idx_orders_user_id on public.orders(user_id);
create index if not exists idx_order_items_order_id on public.order_items(order_id);
create index if not exists idx_order_items_product_id on public.order_items(product_id);
create index if not exists idx_product_enquiries_product_id on public.product_enquiries(product_id);
create index if not exists idx_product_enquiries_user_id on public.product_enquiries(user_id);
create index if not exists idx_quote_requests_user_id on public.quote_requests(user_id);
create index if not exists idx_quote_requests_created_at on public.quote_requests(created_at);
create index if not exists idx_quote_request_items_quote_id on public.quote_request_items(quote_request_id);
create index if not exists idx_quote_request_items_product_id on public.quote_request_items(product_id);
create index if not exists idx_user_preferences_user_id on public.user_preferences(user_id);
create index if not exists idx_cart_items_user_id on public.cart_items(user_id);

insert into public.users (id, name, email, password, role)
values
  (
    1,
    'Admin User',
    'admin@ramanisteelhouse.com',
    '$2a$10$6p7u7h7h7h7h7h7h7h7h7u7h7h7h7h7h7h7h7h7h7h7h7h7h7h7h7',
    'admin'
  )
on conflict (email) do nothing;

insert into public.categories (id, name, slug, image, description)
values
  (
    1,
    'Stainless Steel',
    'stainless-steel',
    'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
    null
  ),
  (
    2,
    'Titanium Alloys',
    'titanium-alloys',
    'https://images.unsplash.com/photo-1535813548-6601f6945379?auto=format&fit=crop&w=800&q=80',
    null
  ),
  (
    3,
    'Nickel Alloys',
    'nickel-alloys',
    'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=800&q=80',
    null
  ),
  (
    4,
    'Industrial Valves',
    'industrial-valves',
    'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=800&q=80',
    null
  ),
  (
    5,
    'Fasteners',
    'fasteners',
    'https://images.unsplash.com/photo-1530124560676-587cad321376?auto=format&fit=crop&w=800&q=80',
    null
  )
on conflict (slug) do update set
  name = excluded.name,
  image = excluded.image,
  description = excluded.description;

insert into public.products (
  id,
  category_id,
  name,
  slug,
  description,
  price,
  image,
  astm_value,
  uns_value,
  dimensions,
  is_featured,
  stock
)
values
  (
    1,
    1,
    'SS 304 Pipe',
    'ss-304-pipe',
    'High quality stainless steel 304 seamless pipe.',
    450.00,
    'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=800&q=80',
    'ASTM A312',
    'S30400',
    '1/2" to 24"',
    true,
    100
  ),
  
  (
    2,
    1,
    'SS 316 Sheet',
    'ss-316-sheet',
    'Corrosion resistant SS 316 cold rolled sheet.',
    1200.00,
    'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=800&q=80',
    'ASTM A240',
    'S31600',
    '1mm to 50mm',
    true,
    50
  ),
  (
    3,
    2,
    'Titanium Grade 2 Bar',
    'titanium-grade-2-bar',
    'Pure titanium grade 2 round bar for industrial use.',
    2500.00,
    'https://images.unsplash.com/photo-1535813548-6601f6945379?auto=format&fit=crop&w=800&q=80',
    'ASTM B348',
    'R50400',
    '10mm to 200mm',
    true,
    30
  ),
  (
    4,
    4,
    'Gate Valve 6 Inch',
    'gate-valve-6-inch',
    'Heavy duty industrial gate valve for fluid control.',
    8500.00,
    'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=800&q=80',
    'API 600',
    'N/A',
    '6 Inch',
    true,
    15
  )
on conflict (slug) do update set
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  image = excluded.image,
  astm_value = excluded.astm_value,
  uns_value = excluded.uns_value,
  dimensions = excluded.dimensions,
  is_featured = excluded.is_featured,
  stock = excluded.stock;

insert into public.ads (
  id,
  title,
  subtitle,
  cta_text,
  cta_url,
  image_url,
  badge,
  discount_percent,
  show_banner,
  show_popup,
  is_active,
  start_at,
  end_at,
  priority
)
values
  (
    1,
    'Launch Offer Sale',
    'New product introductions with limited-time discounts.',
    'View Offers',
    '/products',
    'https://images.unsplash.com/photo-1535813548-6601f6945379?auto=format&fit=crop&w=1200&q=80',
    'New Product',
    18,
    true,
    true,
    true,
    now() - interval '1 day',
    now() + interval '30 days',
    10
  )
on conflict (id) do update set
  title = excluded.title,
  subtitle = excluded.subtitle,
  cta_text = excluded.cta_text,
  cta_url = excluded.cta_url,
  image_url = excluded.image_url,
  badge = excluded.badge,
  discount_percent = excluded.discount_percent,
  show_banner = excluded.show_banner,
  show_popup = excluded.show_popup,
  is_active = excluded.is_active,
  start_at = excluded.start_at,
  end_at = excluded.end_at,
  priority = excluded.priority;

select setval(
  pg_get_serial_sequence('public.users', 'id'),
  greatest((select coalesce(max(id), 1) from public.users), 1),
  true
);
select setval(
  pg_get_serial_sequence('public.categories', 'id'),
  greatest((select coalesce(max(id), 1) from public.categories), 1),
  true
);
select setval(
  pg_get_serial_sequence('public.products', 'id'),
  greatest((select coalesce(max(id), 1) from public.products), 1),
  true
);
select setval(
  pg_get_serial_sequence('public.ads', 'id'),
  greatest((select coalesce(max(id), 1) from public.ads), 1),
  true
);
select setval(
  pg_get_serial_sequence('public.orders', 'id'),
  greatest((select coalesce(max(id), 1) from public.orders), 1),
  true
);
select setval(
  pg_get_serial_sequence('public.order_items', 'id'),
  greatest((select coalesce(max(id), 1) from public.order_items), 1),
  true
);
select setval(
  pg_get_serial_sequence('public.visitor_logs', 'id'),
  greatest((select coalesce(max(id), 1) from public.visitor_logs), 1),
  true
);
select setval(
  pg_get_serial_sequence('public.product_enquiries', 'id'),
  greatest((select coalesce(max(id), 1) from public.product_enquiries), 1),
  true
);
select setval(
  pg_get_serial_sequence('public.quote_requests', 'id'),
  greatest((select coalesce(max(id), 1) from public.quote_requests), 1),
  true
);
select setval(
  pg_get_serial_sequence('public.quote_request_items', 'id'),
  greatest((select coalesce(max(id), 1) from public.quote_request_items), 1),
  true
);

alter table if exists public.users add column if not exists provider text;
alter table if exists public.users add column if not exists google_id text;
alter table if exists public.users add column if not exists avatar_url text;

alter table if exists public.user_preferences add column if not exists locale text;
alter table if exists public.user_preferences add column if not exists country_code text;
alter table if exists public.user_preferences add column if not exists currency text;
alter table if exists public.user_preferences add column if not exists postal_code text;
alter table if exists public.user_preferences add column if not exists preferences jsonb;
alter table if exists public.user_preferences add column if not exists updated_at timestamptz not null default now();

alter table if exists public.visitor_logs add column if not exists user_id bigint references public.users(id) on delete set null;
alter table if exists public.product_enquiries add column if not exists user_id bigint references public.users(id) on delete set null;
alter table if exists public.quote_requests add column if not exists user_id bigint references public.users(id) on delete set null;

commit;
