import pool, { query, queryOne } from "./db.js";

const CRM_WEBHOOK_URL = process.env.CRM_WEBHOOK_URL;
const CRM_AUTH_HEADER = process.env.CRM_AUTH_HEADER || "Authorization";
const CRM_AUTH_VALUE = process.env.CRM_AUTH_VALUE;
const CRM_TIMEOUT_MS = Number(process.env.CRM_TIMEOUT_MS || 10000);
const CRM_MAX_ATTEMPTS = Number(process.env.CRM_MAX_ATTEMPTS || 6);
const CRM_RETRY_BASE_MS = Number(process.env.CRM_RETRY_BASE_MS || 60000);
const CRM_POLL_INTERVAL_MS = Number(process.env.CRM_POLL_INTERVAL_MS || 15000);
const CRM_BATCH_SIZE = Number(process.env.CRM_BATCH_SIZE || 10);

export const CRM_API_KEY = process.env.CRM_API_KEY;

/**
 * The payload contract sent to the CRM/ERP. Keep this stable - the CRM side maps
 * these fields onto its own lead record.
 */
export type CrmLead = {
  external_id: string;
  source: "website_enquiry" | "website_rfq";
  received_at: string;
  contact: {
    full_name: string | null;
    email: string | null;
    phone: string | null;
    company: string | null;
    location: string | null;
    gst_number?: string | null;
    pin_code?: string | null;
  };
  interest: {
    product_id: string | number | null;
    product_name: string | null;
    requirement: string | null;
    thickness?: string | null;
    quantity: string | null;
    message: string | null;
  };
  items?: Array<{
    product_id: string | number | null;
    product_name: string | null;
    category_name: string | null;
    quantity: number | null;
    unit_price: number | null;
    line_total: number | null;
  }>;
  totals?: {
    subtotal: number | null;
    gst: number | null;
    total: number | null;
    currency: string | null;
    items_count: number | null;
    shipping_option: string | null;
  };
  meta: {
    site_user_id: number | null;
    locale?: string | null;
    page_source?: string | null;
    user_agent?: string | null;
  };
};

type SyncRow = {
  id: number;
  external_id: string;
  payload: CrmLead;
  attempts: number;
};

const toNumber = (value: unknown): number | null => {
  if (value === null || value === undefined || value === "") return null;
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : null;
};

const toText = (value: unknown): string | null => {
  if (value === null || value === undefined) return null;
  const text = String(value).trim();
  return text || null;
};

/**
 * Creates the queue table. Follows the in-code migration pattern the rest of this
 * app uses, so a fresh deploy needs no manual SQL step.
 */
export const ensureCrmSyncSchema = async () => {
  try {
    await query(`
      CREATE TABLE IF NOT EXISTS public.crm_lead_sync (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        external_id text NOT NULL UNIQUE,
        source text NOT NULL,
        source_id bigint,
        payload jsonb NOT NULL,
        status text NOT NULL DEFAULT 'pending',
        attempts integer NOT NULL DEFAULT 0,
        last_error text,
        crm_record_id text,
        next_attempt_at timestamptz NOT NULL DEFAULT now(),
        delivered_at timestamptz,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now()
      )
    `);
    await query(
      `CREATE INDEX IF NOT EXISTS crm_lead_sync_claim_idx
         ON public.crm_lead_sync (next_attempt_at) WHERE status = 'pending'`
    );
    await query(`CREATE INDEX IF NOT EXISTS crm_lead_sync_status_idx ON public.crm_lead_sync (status)`);
    await query(`CREATE INDEX IF NOT EXISTS crm_lead_sync_created_at_idx ON public.crm_lead_sync (created_at)`);
    // Lead contact details must never be readable with the browser-side publishable
    // key. No policies means deny-all; the API connects as the owner, which is exempt.
    await query(`ALTER TABLE public.crm_lead_sync ENABLE ROW LEVEL SECURITY`);
  } catch (error) {
    console.error("Failed to ensure crm_lead_sync schema is up to date", error);
  }
};

export const buildEnquiryLead = (
  enquiryId: number,
  input: Record<string, any>,
  userId: number | null
): CrmLead => ({
  external_id: `enquiry:${enquiryId}`,
  source: "website_enquiry",
  received_at: new Date().toISOString(),
  contact: {
    full_name: toText(input.fullName),
    email: toText(input.email),
    phone: toText(input.phone),
    company: toText(input.company),
    location: toText(input.location),
  },
  interest: {
    product_id: input.productId ?? null,
    product_name: toText(input.productName),
    requirement: toText(input.requirement),
    thickness: toText(input.thickness),
    quantity: toText(input.quantity),
    message: toText(input.message),
  },
  meta: {
    site_user_id: userId,
  },
});

export const buildQuoteLead = (
  quoteId: number,
  body: Record<string, any>,
  userId: number | null,
  itemsCount: number
): CrmLead => {
  const customer = body.customer ?? {};
  const summary = body.summary ?? {};
  const meta = body.meta ?? {};
  const items = Array.isArray(body.items) ? body.items : [];

  return {
    external_id: `quote:${quoteId}`,
    source: "website_rfq",
    received_at: new Date().toISOString(),
    contact: {
      full_name: toText(customer.full_name ?? customer.name),
      email: toText(customer.email),
      phone: toText(customer.phone_full ?? customer.phone_number),
      company: toText(customer.company),
      location: toText(customer.location),
      gst_number: toText(customer.gst_number),
      pin_code: toText(customer.pin_code),
    },
    interest: {
      product_id: null,
      product_name: null,
      requirement: "Cart quote request",
      quantity: String(itemsCount),
      message: null,
    },
    items: items.map((item: any) => ({
      product_id: item.product_id ?? null,
      product_name: toText(item.product_name),
      category_name: toText(item.category_name),
      quantity: toNumber(item.quantity),
      unit_price: toNumber(item.unit_price),
      line_total: toNumber(item.line_total),
    })),
    totals: {
      subtotal: toNumber(summary.subtotal),
      gst: toNumber(summary.gst),
      total: toNumber(summary.total),
      currency: toText(summary.currency),
      items_count: itemsCount,
      shipping_option: toText(body.shipping_option),
    },
    meta: {
      site_user_id: userId,
      locale: toText(summary.locale),
      page_source: toText(meta.source),
      user_agent: toText(meta.user_agent),
    },
  };
};

/**
 * Records the lead for delivery. The website database stays the source of truth,
 * so a CRM outage can never lose a lead - it just delays it.
 */
export const enqueueLead = async (
  source: string,
  sourceId: number,
  lead: CrmLead
): Promise<void> => {
  try {
    await query(
      `INSERT INTO crm_lead_sync (external_id, source, source_id, payload)
       VALUES ($1, $2, $3, $4)
       ON CONFLICT (external_id) DO NOTHING`,
      [lead.external_id, source, sourceId, JSON.stringify(lead)]
    );
  } catch (error) {
    console.error("Failed to queue CRM lead", lead.external_id, error);
    return;
  }
  void processQueue();
};

const deliverLead = async (lead: CrmLead): Promise<{ crmRecordId: string | null }> => {
  if (!CRM_WEBHOOK_URL) {
    throw new Error("CRM_WEBHOOK_URL is not configured");
  }

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    "X-Idempotency-Key": lead.external_id,
  };
  if (CRM_AUTH_VALUE) {
    headers[CRM_AUTH_HEADER] = CRM_AUTH_VALUE;
  }

  const response = await fetch(CRM_WEBHOOK_URL, {
    method: "POST",
    headers,
    body: JSON.stringify(lead),
    signal: AbortSignal.timeout(CRM_TIMEOUT_MS),
  });

  const text = await response.text();
  if (!response.ok) {
    throw new Error(`CRM responded ${response.status}: ${text.slice(0, 500)}`);
  }

  let crmRecordId: string | null = null;
  try {
    const parsed = JSON.parse(text);
    const candidate = parsed?.id ?? parsed?.lead_id ?? parsed?.record_id ?? parsed?.data?.id;
    if (candidate !== undefined && candidate !== null) {
      crmRecordId = String(candidate);
    }
  } catch {
    // Non-JSON success response is fine; we just have no CRM id to store.
  }

  return { crmRecordId };
};

let isProcessing = false;
let missingConfigWarned = false;

/**
 * Claims due leads and pushes them. FOR UPDATE SKIP LOCKED keeps this safe when
 * more than one server process runs against the same database.
 */
export const processQueue = async (): Promise<void> => {
  if (isProcessing) return;
  if (!CRM_WEBHOOK_URL) {
    if (!missingConfigWarned) {
      console.warn(
        "CRM_WEBHOOK_URL is not set. Leads are being queued in crm_lead_sync but not pushed. " +
          "Set it, or have your CRM pull from GET /api/crm/leads."
      );
      missingConfigWarned = true;
    }
    return;
  }

  isProcessing = true;
  try {
    const client = await pool.connect();
    let rows: SyncRow[] = [];
    try {
      await client.query("BEGIN");
      const claimed = await client.query<SyncRow>(
        `SELECT id, external_id, payload, attempts
           FROM crm_lead_sync
          WHERE status = 'pending' AND next_attempt_at <= now()
          ORDER BY created_at ASC
          LIMIT $1
          FOR UPDATE SKIP LOCKED`,
        [CRM_BATCH_SIZE]
      );
      rows = claimed.rows;
      if (rows.length > 0) {
        await client.query(
          `UPDATE crm_lead_sync
              SET next_attempt_at = now() + ($2 || ' milliseconds')::interval,
                  updated_at = now()
            WHERE id = ANY($1::bigint[])`,
          [rows.map((row) => row.id), String(CRM_TIMEOUT_MS + 5000)]
        );
      }
      await client.query("COMMIT");
    } catch (error) {
      await client.query("ROLLBACK");
      throw error;
    } finally {
      client.release();
    }

    for (const row of rows) {
      try {
        const { crmRecordId } = await deliverLead(row.payload);
        await query(
          `UPDATE crm_lead_sync
              SET status = 'sent',
                  attempts = attempts + 1,
                  crm_record_id = $2,
                  last_error = NULL,
                  delivered_at = now(),
                  updated_at = now()
            WHERE id = $1`,
          [row.id, crmRecordId]
        );
      } catch (error) {
        const attempts = row.attempts + 1;
        const exhausted = attempts >= CRM_MAX_ATTEMPTS;
        const backoffMs = CRM_RETRY_BASE_MS * Math.pow(2, Math.min(attempts - 1, 8));
        const messageText = error instanceof Error ? error.message : String(error);

        await query(
          `UPDATE crm_lead_sync
              SET status = $3,
                  attempts = $2,
                  last_error = $4,
                  next_attempt_at = now() + ($5 || ' milliseconds')::interval,
                  updated_at = now()
            WHERE id = $1`,
          [row.id, attempts, exhausted ? "failed" : "pending", messageText.slice(0, 1000), String(backoffMs)]
        );

        console.error(
          `CRM push failed for ${row.external_id} (attempt ${attempts}/${CRM_MAX_ATTEMPTS})`,
          messageText
        );
      }
    }
  } catch (error) {
    console.error("CRM sync worker error", error);
  } finally {
    isProcessing = false;
  }
};

export const startCrmSyncWorker = (): void => {
  const timer = setInterval(() => void processQueue(), CRM_POLL_INTERVAL_MS);
  timer.unref?.();
  void processQueue();
};

/** Moves exhausted leads back into the pending queue. */
export const retryFailedLeads = async (externalId?: string): Promise<number> => {
  const rows = await query<{ id: number }>(
    `UPDATE crm_lead_sync
        SET status = 'pending',
            attempts = 0,
            next_attempt_at = now(),
            updated_at = now()
      WHERE status = 'failed'
        AND ($1::text IS NULL OR external_id = $1)
      RETURNING id`,
    [externalId ?? null]
  );
  if (rows.length > 0) void processQueue();
  return rows.length;
};

/** Pull-mode access for CRMs that cannot receive inbound webhooks. */
export const listLeads = async (options: { since?: string; status?: string; limit: number }) =>
  query(
    `SELECT external_id, source, source_id, payload, status, crm_record_id, created_at, delivered_at
       FROM crm_lead_sync
      WHERE ($1::timestamptz IS NULL OR created_at > $1)
        AND ($2::text IS NULL OR status = $2)
      ORDER BY created_at ASC
      LIMIT $3`,
    [options.since ?? null, options.status ?? null, options.limit]
  );

export const acknowledgeLead = async (externalId: string, crmRecordId: string | null) =>
  queryOne(
    `UPDATE crm_lead_sync
        SET status = 'sent',
            crm_record_id = COALESCE($2, crm_record_id),
            last_error = NULL,
            delivered_at = now(),
            updated_at = now()
      WHERE external_id = $1
      RETURNING external_id, status, crm_record_id`,
    [externalId, crmRecordId]
  );
