/**
 * Writes src/lib/productLinks.ts, the catalogue as a flat list the footer can render.
 *
 * The footer is on every page and does no data fetching — putting a fetch there would mean one
 * request per page view for links that change a few times a year. So the list is baked in at
 * build time instead, the same approach scripts/sync-product-images.ts takes for photos.
 *
 * Why the footer needs it at all: a product page was previously reachable only from /products,
 * from the sitemap, and from the related-products block on its siblings. Crawlers treat a URL
 * with no site-wide entry point as low priority, which is the structural advantage the
 * marketplace catalogues have — every one of their pages links to every product.
 *
 * Degrades like the sitemap generator: a build that cannot reach the database leaves the
 * committed file alone rather than writing an empty catalogue into the footer.
 */
import { writeFileSync, readFileSync, existsSync } from "fs";
import path from "path";

const OUTPUT_PATH = path.resolve(process.cwd(), "src/lib/productLinks.ts");

const render = (rows: Array<{ slug: string; name: string }>) =>
  `// GENERATED by scripts/generate-product-links.ts — do not edit by hand.
//
// The catalogue as a flat list of links, for site-wide navigation. The footer renders these on
// every page, which is what gives each product URL an entry point from everywhere on the site
// rather than only from /products and the sitemap.
//
// Names are de-duplicated: two catalogue rows are both called "Ni Custom", and two identical
// links with identical anchor text tell a search engine nothing about either page.

export type ProductLink = { slug: string; name: string };

export const PRODUCT_LINKS: readonly ProductLink[] = [
${rows.map((row) => `  { slug: ${JSON.stringify(row.slug)}, name: ${JSON.stringify(row.name)} },`).join("\n")}
];
`;

async function main() {
  let rows: Array<{ slug: string; name: string }>;

  try {
    // Dynamic, so a missing build-time database connection is a warning rather than an import
    // error that fails the whole build.
    const { query } = await import("../db.js");
    rows = await query<{ slug: string; name: string }>(
      `SELECT slug, name FROM products
        WHERE slug IS NOT NULL AND slug <> '' AND name IS NOT NULL AND name <> ''
        -- is_featured first so the footer leads with whatever the catalogue promotes, then
        -- alphabetical, which keeps the generated file stable between builds.
        ORDER BY is_featured DESC NULLS LAST, name`
    );
  } catch (error) {
    console.warn("[product-links] Database unavailable; leaving src/lib/productLinks.ts as committed.", error);
    return;
  }

  // Two rows share the name "Ni Custom". Rendering both would put two identical anchors on
  // every page of the site, which splits the signal between them and helps neither.
  const seen = new Set<string>();
  const unique = rows.filter((row) => {
    const key = row.name.trim().toLowerCase();
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });

  if (!unique.length) {
    console.warn("[product-links] Query returned no products; leaving the committed file alone.");
    return;
  }

  const next = render(unique);
  if (existsSync(OUTPUT_PATH) && readFileSync(OUTPUT_PATH, "utf-8") === next) {
    console.log(`[product-links] src/lib/productLinks.ts already current (${unique.length} products).`);
    return;
  }

  writeFileSync(OUTPUT_PATH, next);
  console.log(`[product-links] Wrote ${unique.length} products (${rows.length - unique.length} duplicate name(s) dropped).`);
}

main().catch((error) => {
  console.warn("[product-links] Generator failed; leaving the committed file alone.", error);
});
