/**
 * Writes public/_redirects, Netlify's routing table, from the route lists the renderer already
 * owns.
 *
 * vercel.json hand-lists every SSR route, and that list has drifted from the code before — a
 * landing page added to landingPages.ts is live in React but invisible to crawlers until
 * somebody remembers the routing file. Generating the table from LANDING_PATHS and the snapshot
 * route keys removes the second place to remember: add a route to the renderer and the next
 * build routes it.
 *
 * Vite copies public/ into dist/, so the generated file ships with the build. It runs in
 * prebuild, before `vite build`, for that reason.
 *
 * Netlify's rules are first-match-wins, and — unlike Vercel's — are matched case-sensitively,
 * which is what the ordering below relies on. Static files win over a rule automatically unless
 * the rule is forced with `!`; only "/" needs that, because it is the one SSR route that also
 * exists as a real file (dist/index.html).
 */
import { writeFileSync, readFileSync, existsSync } from "fs";
import path from "path";
import { LANDING_PATHS } from "../src/lib/landingPages.js";
// Imported from snapshotRoutes, not seoSnapshot: the latter pulls in db.ts, which throws at
// module load without a connection string. This file must still emit a correct routing table on
// a build that cannot reach Postgres, because a missing table 404s the entire site.
import { STATIC_SNAPSHOT_ROUTES, NOINDEX_SNAPSHOT_ROUTES, SPA_ONLY_ROUTES } from "../src/lib/snapshotRoutes.js";

const RENDER = "/.netlify/functions/render";
const API = "/.netlify/functions/api";

/**
 * A rewrite to a Netlify function leaves the function seeing its own path, not the visitor's,
 * so the route is passed through explicitly. ssrHandler.ts reads ?path= in preference to
 * req.url for exactly this reason.
 */
const ssr = (route: string) => `${route}  ${RENDER}?path=${route}  200`;

// Old URLs that were live long enough to be linked and indexed. They are 301s rather than
// rewrites so the duplicate drops out of the index instead of being served under two URLs.
const LEGACY_REDIRECTS: Array<[string, string]> = [
  ["/blog/Why-99.6-Purity-Matters", "/blog/why-nickel-purity-matters"],
  ["/blog/Manufacturers-Guide", "/blog/sourcing-custom-stamped-nickel-busbars"],
  ["/blog/Nickel-Strip-Manufacturer-for-UK-Battery-Industry", "/blog/nickel-strip-manufacturer-uk-battery-industry"],
  ["/blog/Pure-Nickel-Strip-vs-Nickel-Plated-Steel-Strip:-Complete-Comparison", "/blog/pure-nickel-strip-vs-nickel-plated-steel-strip"],
  ["/blog/Pure-Nickel-Strip-vs-Nickel-Plated-Steel-Strip%3A-Complete-Comparison", "/blog/pure-nickel-strip-vs-nickel-plated-steel-strip"],
];

const lines: string[] = [
  "# GENERATED by scripts/generate-netlify-redirects.ts — do not edit by hand.",
  "# Rules are first-match-wins. Static files take precedence unless a rule ends in '!'.",
  "",
  "# The API and the merchant feed. The caller's own /api prefix is kept in the rewritten",
  "# path so that, after serverless-http strips Netlify's prefix, Express sees /api/*.",
  `/api/*  ${API}/api/:splat  200`,
  `/merchant-feed.xml  ${API}/merchant-feed.xml  200`,
  "",
  "# Legacy blog URLs.",
  ...LEGACY_REDIRECTS.map(([from, to]) => `${from}  ${to}  301!`),
  "",
  "# The homepage is the one SSR route that is also a real file, so it must be forced.",
  `/  ${RENDER}?path=/  200!`,
  "",
  "# Listing pages.",
  ssr("/products"),
  ssr("/categories"),
  ssr("/blog"),
  "",
  "# Static-content routes (about, contact, calculator, …). '/' is filtered out because it is",
  "# already emitted above with the force flag it needs.",
  ...STATIC_SNAPSHOT_ROUTES.filter((route) => route !== "/").map(ssr),
  "",
  "# Routes served with noindex (cart, checkout, login).",
  ...NOINDEX_SNAPSHOT_ROUTES.map(ssr),
  "",
  "# App routes with no snapshot of their own. Without these the catch-all 404 below would",
  "# swallow a real page.",
  ...SPA_ONLY_ROUTES.map(ssr),
  "",
  "# Category and location landing pages.",
  ...LANDING_PATHS.map(ssr),
  "",
  "# Per-item pages. :splat carries the slug through to the renderer.",
  `/product/*  ${RENDER}?path=/product/:splat  200`,
  `/blog/*  ${RENDER}?path=/blog/:splat  200`,
  "",
  "# Anything else is genuinely not a page. Matching Vercel's behaviour, this is a real 404",
  "# rather than the SPA shell, so an unknown URL is not indexed as a soft 404.",
  "/*  /404.html  404",
  "",
];

const outputPath = path.resolve(process.cwd(), "public/_redirects");
const next = lines.join("\n");

// Byte-identical rewrites churn the working tree for nothing; skip them so `git status` after a
// build only shows a real routing change.
if (existsSync(outputPath) && readFileSync(outputPath, "utf-8") === next) {
  console.log(`[netlify-redirects] public/_redirects already current (${lines.length} lines).`);
} else {
  writeFileSync(outputPath, next);
  console.log(
    `[netlify-redirects] Wrote public/_redirects — ${STATIC_SNAPSHOT_ROUTES.length} static, ` +
      `${NOINDEX_SNAPSHOT_ROUTES.length} noindex, ${LANDING_PATHS.length} landing routes.`
  );
}
