/**
 * Downloads every product photo to public/img/products/<slug>.webp and writes the manifest
 * that names them.
 *
 * Product photos live in Supabase Storage behind signed URLs. That is a single point of
 * failure for every thumbnail on the site: revoke a token, re-upload a file under a new name,
 * flip the bucket to private, or simply have Supabase be down, and the product grid fills with
 * broken images. Keeping a copy on our own domain means the worst case is a slightly stale
 * photo rather than no photo.
 *
 * The copies are a *fallback*, not the primary source — /api/product-image still fetches
 * upstream first, so a photo replaced in the CMS appears immediately without re-running this.
 * Re-run it when products are added or photos are changed:
 *
 *     npx tsx scripts/sync-product-images.ts
 *
 * Requires the same DB connection as the rest of the build; with no database reachable it
 * leaves the existing files and manifest untouched rather than emptying them.
 */
import { existsSync, mkdirSync, readdirSync, writeFileSync } from "fs";
import path from "path";
import sharp from "sharp";

const LIVE_API_ORIGIN = process.env.SYNC_API_ORIGIN || "https://www.nickelbusbar.com";
const OUTPUT_DIR = path.resolve(process.cwd(), "public/img/products");
const MANIFEST_PATH = path.resolve(process.cwd(), "src/lib/productImageLocal.ts");
// Thumbnails render at 600px at most; the detail page hero is the largest use at ~900px.
const MAX_WIDTH = 900;
const WEBP_QUALITY = 78;

const writeManifest = (slugs: string[]) => {
  const sorted = [...slugs].sort();
  const body = `// GENERATED by scripts/sync-product-images.ts — do not edit by hand.
//
// Slugs with a downloaded photo under public/img/products/. Both the image proxy in apiApp.ts
// and the <ProductThumbnail> fallback consult this before falling back to the generic
// placeholder, so a product with a local copy shows its own photo rather than the logo.

export const LOCAL_PRODUCT_IMAGE_SLUGS: ReadonlySet<string> = new Set([
${sorted.map((slug) => `  ${JSON.stringify(slug)},`).join("\n")}
]);

/** Root-relative path to the downloaded copy, or null when there is none. */
export function localProductImagePath(slug?: string | null): string | null {
  const clean = slug?.trim();
  if (!clean || !LOCAL_PRODUCT_IMAGE_SLUGS.has(clean)) return null;
  return \`/img/products/\${encodeURIComponent(clean)}.webp\`;
}
`;
  writeFileSync(MANIFEST_PATH, body, "utf-8");
};

async function main() {
  let products: Array<{ slug: string; image: string | null }> = [];
  try {
    const { query } = await import("../db.js");
    products = await query<{ slug: string; image: string | null }>(
      `SELECT slug, image FROM products
        WHERE slug IS NOT NULL AND slug <> '' AND image IS NOT NULL AND image <> ''
        ORDER BY slug`
    );
  } catch (error) {
    // The published /api/products returns the same slug and image fields. Falling back to it
    // means this can be re-run from a checkout with no database credentials — which is the
    // usual case for whoever is just refreshing the photos.
    console.warn("[product-images] Database unreachable; reading the live API instead.", error);
    try {
      const response = await fetch(`${LIVE_API_ORIGIN}/api/products`);
      if (!response.ok) throw new Error(`API returned ${response.status}`);
      const rows = (await response.json()) as Array<{ slug?: string; image?: string | null }>;
      products = rows
        .filter((row): row is { slug: string; image: string } => Boolean(row.slug && row.image))
        .map((row) => ({ slug: row.slug, image: row.image }));
    } catch (apiError) {
      console.error("[product-images] Live API unavailable too; leaving existing copies alone.", apiError);
      return;
    }
  }

  if (!products.length) {
    console.warn("[product-images] No products with photos returned; leaving existing copies alone.");
    return;
  }

  mkdirSync(OUTPUT_DIR, { recursive: true });

  const saved: string[] = [];
  const failed: string[] = [];

  for (const product of products) {
    const source = product.image?.trim();
    if (!source || !/^https?:\/\//i.test(source)) {
      failed.push(product.slug);
      continue;
    }
    try {
      const response = await fetch(source, { redirect: "follow" });
      const contentType = (response.headers.get("content-type") || "").toLowerCase();
      if (!response.ok || !contentType.startsWith("image/")) {
        console.warn(`[product-images] ${product.slug}: ${response.status} ${contentType || "(no type)"}`);
        failed.push(product.slug);
        continue;
      }
      const input = Buffer.from(await response.arrayBuffer());
      // withoutEnlargement: a photo already smaller than MAX_WIDTH is re-encoded, not upscaled.
      const output = await sharp(input)
        .resize(MAX_WIDTH, null, { fit: "inside", withoutEnlargement: true })
        .webp({ quality: WEBP_QUALITY })
        .toBuffer();
      writeFileSync(path.join(OUTPUT_DIR, `${product.slug}.webp`), output);
      saved.push(product.slug);
      console.log(
        `[product-images] ${product.slug}: ${(input.length / 1024).toFixed(0)}KB -> ${(output.length / 1024).toFixed(0)}KB`
      );
    } catch (error) {
      console.warn(`[product-images] ${product.slug} failed`, error);
      failed.push(product.slug);
    }
  }

  // A product whose download failed this run may still have a copy from a previous one; the
  // manifest describes what is on disk, not what this run managed to fetch.
  const onDisk = existsSync(OUTPUT_DIR)
    ? readdirSync(OUTPUT_DIR)
        .filter((file) => file.endsWith(".webp"))
        .map((file) => file.slice(0, -".webp".length))
    : [];

  writeManifest(onDisk);
  console.log(
    `[product-images] ${saved.length} saved, ${failed.length} failed, ${onDisk.length} in manifest.`
  );
}

main()
  .catch((error) => {
    console.error("[product-images] Sync failed; existing copies left untouched.", error);
  })
  .finally(() => {
    process.exit(0);
  });
