/**
 * Downloads every product photo to public/img/products/ under a descriptive filename, and
 * writes the manifest that maps each product slug to the file it was given.
 *
 * Product photos live in Supabase Storage behind signed URLs. That is a single point of
 * failure for every thumbnail on the site: revoke a token, re-upload a file under a new name,
 * flip the bucket to private, or simply have Supabase be down, and the product grid fills with
 * broken images. Keeping a copy on our own domain means the worst case is a slightly stale
 * photo rather than no photo.
 *
 * The copies are a *fallback*, not the primary source — /api/product-image still fetches
 * upstream first, so a photo replaced in the CMS appears immediately without re-running this.
 * Re-run it when products are added or photos are changed:
 *
 *     npx tsx scripts/sync-product-images.ts
 *
 * Requires the same DB connection as the rest of the build; with no database reachable it
 * leaves the existing files and manifest untouched rather than emptying them.
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, renameSync, writeFileSync } from "fs";
import path from "path";
import sharp from "sharp";

const LIVE_API_ORIGIN = process.env.SYNC_API_ORIGIN || "https://www.nickelbusbar.com";
const OUTPUT_DIR = path.resolve(process.cwd(), "public/img/products");
const MANIFEST_PATH = path.resolve(process.cwd(), "src/lib/productImageLocal.ts");
// Thumbnails render at 600px at most; the detail page hero is the largest use at ~900px.
const MAX_WIDTH = 900;
const WEBP_QUALITY = 78;

/** Words that already identify the kind of product, so a suffix would only repeat them. */
const TYPE_WORDS = /\b(strip|strips|busbar|busbars)\b/i;

const slugify = (value: string) =>
  value
    .toLowerCase()
    // Parentheticals are dropped rather than transliterated: on these products they hold the
    // ASTM designation, and several of those on record look wrong for nickel strip (B16 and
    // B17 are copper-alloy standards; B162 is the nickel sheet/strip one). A filename is a
    // permanent, quotable URL, so an unverified standard does not belong in it.
    .replace(/\([^)]*\)/g, " ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

/**
 * A readable, keyword-bearing filename for a product photo, built from the product's own name
 * and slug — never from anything invented.
 *
 * The photos were previously saved as <slug>.webp, which gave URLs like
 * /img/products/ni-custom-custom.webp: meaningless to an image crawler, which reads the file
 * name as one of the few signals it has about what a photo shows, alongside alt text and the
 * text around it. The name column is the descriptive text the business already wrote, so the
 * filename is derived from it and the slug is used only to keep two similar products apart.
 *
 * Every token of the slug that the name does not already cover is appended, which is what
 * guarantees uniqueness: two products can share a name (there are two called "Ni Custom") but
 * not a slug, so the differing slug token always lands in the filename.
 */
export function descriptiveImageFilename(slug: string, name?: string | null): string {
  const fromName = slugify(name?.trim() || "") || slugify(slug);
  const nameTokens = new Set(fromName.split("-").filter(Boolean));
  const extraTokens = slugify(slug)
    .split("-")
    .filter((token) => token && !nameTokens.has(token));

  const base = [fromName, ...extraTokens].filter(Boolean).join("-");
  // "Copper Busbar" and "Plain Nickel Strips" already say what they are; "Ni 18650 3P H-type"
  // does not, and is the case the suffix exists for.
  return TYPE_WORDS.test(base) ? base : `${base}-nickel-strip`;
}

const writeManifest = (entries: Array<[string, string]>) => {
  const sorted = [...entries].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  const body = `// GENERATED by scripts/sync-product-images.ts — do not edit by hand.
//
// Maps each product slug to the descriptive filename its photo was saved under in
// public/img/products/. Both the image proxy in apiApp.ts and the <ProductThumbnail> fallback
// consult this before falling back to the generic placeholder, so a product with a local copy
// shows its own photo rather than the logo.
//
// The filename is not the slug: it is built from the product's name so the image URL reads as
// a description of the photo, which is one of the few things an image crawler can use. Old
// <slug>.webp URLs still resolve — both routing tables send a miss under /img/products/ to the
// /api/product-image proxy, which answers by slug.

const LOCAL_PRODUCT_IMAGE_FILES: ReadonlyMap<string, string> = new Map([
${sorted.map(([slug, file]) => `  [${JSON.stringify(slug)}, ${JSON.stringify(file)}],`).join("\n")}
]);

/** Slugs with a downloaded photo on disk. */
export const LOCAL_PRODUCT_IMAGE_SLUGS: ReadonlySet<string> = new Set(
  LOCAL_PRODUCT_IMAGE_FILES.keys()
);

/** Root-relative path to the downloaded copy, or null when there is none. */
export function localProductImagePath(slug?: string | null): string | null {
  const clean = slug?.trim();
  if (!clean) return null;
  const file = LOCAL_PRODUCT_IMAGE_FILES.get(clean);
  return file ? \`/img/products/\${file}.webp\` : null;
}
`;
  writeFileSync(MANIFEST_PATH, body, "utf-8");
};

/** The slug -> filename pairs from the last run, so a product that fails today keeps its photo. */
const readPreviousManifest = (): Map<string, string> => {
  const previous = new Map<string, string>();
  if (!existsSync(MANIFEST_PATH)) return previous;
  try {
    const source = readFileSync(MANIFEST_PATH, "utf-8");
    for (const match of source.matchAll(/\[\s*"([^"]+)"\s*,\s*"([^"]+)"\s*\]/g)) {
      previous.set(match[1], match[2]);
    }
  } catch {
    // An unreadable manifest is rebuilt from this run alone.
  }
  return previous;
};

async function main() {
  let products: Array<{ slug: string; name: string | null; image: string | null }> = [];
  try {
    const { query } = await import("../db.js");
    products = await query<{ slug: string; name: string | null; image: string | null }>(
      `SELECT slug, name, image FROM products
        WHERE slug IS NOT NULL AND slug <> '' AND image IS NOT NULL AND image <> ''
        ORDER BY slug`
    );
  } catch (error) {
    // The published /api/products returns the same slug, name and image fields. Falling back to
    // it means this can be re-run from a checkout with no database credentials — which is the
    // usual case for whoever is just refreshing the photos.
    console.warn("[product-images] Database unreachable; reading the live API instead.", error);
    try {
      const response = await fetch(`${LIVE_API_ORIGIN}/api/products`);
      if (!response.ok) throw new Error(`API returned ${response.status}`);
      const rows = (await response.json()) as Array<{
        slug?: string;
        name?: string | null;
        image?: string | null;
      }>;
      products = rows
        .filter((row): row is { slug: string; name: string | null; image: string } =>
          Boolean(row.slug && row.image)
        )
        .map((row) => ({ slug: row.slug, name: row.name ?? null, image: row.image }));
    } catch (apiError) {
      console.error("[product-images] Live API unavailable too; leaving existing copies alone.", apiError);
      return;
    }
  }

  if (!products.length) {
    console.warn("[product-images] No products with photos returned; leaving existing copies alone.");
    return;
  }

  mkdirSync(OUTPUT_DIR, { recursive: true });

  const saved: string[] = [];
  const failed: string[] = [];
  // Starts from the previous run so a product whose download fails today keeps pointing at the
  // copy an earlier run saved, then is filtered against the disk before being written out.
  const manifest = readPreviousManifest();

  for (const product of products) {
    const filename = descriptiveImageFilename(product.slug, product.name);

    // Carry a copy saved under the old <slug>.webp name, or under a previous descriptive name,
    // across to the current one. Renaming rather than re-downloading means an existing photo
    // survives a run that cannot reach the image host.
    for (const legacy of [manifest.get(product.slug), product.slug]) {
      if (!legacy || legacy === filename) continue;
      const from = path.join(OUTPUT_DIR, `${legacy}.webp`);
      const to = path.join(OUTPUT_DIR, `${filename}.webp`);
      if (!existsSync(from)) continue;
      // "Copper-Busbar" -> "copper-busbar" differs only in case, and on Windows and macOS the
      // two names are the same file: existsSync(to) is true, a direct rename is a no-op, and
      // the file keeps its old capitalisation. The deploy targets run Linux, where the case
      // does matter, so the manifest would then point at a filename that is not in the repo.
      // Bouncing through a temporary name makes the rename real on every platform.
      const caseOnly = legacy.toLowerCase() === filename.toLowerCase();
      if (!caseOnly && existsSync(to)) continue;
      if (caseOnly) {
        const staging = path.join(OUTPUT_DIR, `${filename}.rename.webp`);
        renameSync(from, staging);
        renameSync(staging, to);
      } else {
        renameSync(from, to);
      }
      console.log(`[product-images] renamed ${legacy}.webp -> ${filename}.webp`);
    }
    manifest.set(product.slug, filename);

    const source = product.image?.trim();
    if (!source || !/^https?:\/\//i.test(source)) {
      failed.push(product.slug);
      continue;
    }
    try {
      const response = await fetch(source, { redirect: "follow" });
      const contentType = (response.headers.get("content-type") || "").toLowerCase();
      if (!response.ok || !contentType.startsWith("image/")) {
        console.warn(`[product-images] ${product.slug}: ${response.status} ${contentType || "(no type)"}`);
        failed.push(product.slug);
        continue;
      }
      const input = Buffer.from(await response.arrayBuffer());
      // withoutEnlargement: a photo already smaller than MAX_WIDTH is re-encoded, not upscaled.
      const output = await sharp(input)
        .resize(MAX_WIDTH, null, { fit: "inside", withoutEnlargement: true })
        .webp({ quality: WEBP_QUALITY })
        .toBuffer();
      writeFileSync(path.join(OUTPUT_DIR, `${filename}.webp`), output);
      saved.push(product.slug);
      console.log(
        `[product-images] ${product.slug}: ${(input.length / 1024).toFixed(0)}KB -> ${(output.length / 1024).toFixed(0)}KB`
      );
    } catch (error) {
      console.warn(`[product-images] ${product.slug} failed`, error);
      failed.push(product.slug);
    }
  }

  // A product whose download failed this run may still have a copy from a previous one; the
  // manifest describes what is on disk, not what this run managed to fetch.
  const onDisk = new Set(
    existsSync(OUTPUT_DIR)
      ? readdirSync(OUTPUT_DIR)
          .filter((file) => file.endsWith(".webp"))
          .map((file) => file.slice(0, -".webp".length))
      : []
  );
  const entries = [...manifest.entries()].filter(([, file]) => onDisk.has(file));

  writeManifest(entries);
  console.log(
    `[product-images] ${saved.length} saved, ${failed.length} failed, ${entries.length} in manifest.`
  );
}

main()
  .catch((error) => {
    console.error("[product-images] Sync failed; existing copies left untouched.", error);
  })
  .finally(() => {
    process.exit(0);
  });
